In [1]:
pip install tensorflow opencv-python matplotlib

Requirement already satisfied: tensorflow in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (2.21.0)
Requirement already satisfied: opencv-python in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (4.13.0.92)
Requirement already satisfied: matplotlib in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (3.10.8)
Requirement already satisfied: numpy>=1.26.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.2.6)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: keras>=3.12.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (7.34.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: six>=1.12.0 in c:\users\verra halizzah\appdata\roaming\python\python310\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: setuptools in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (57.4.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\verra halizzah\appdata\roaming\python\python310\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: packaging in c:\users\verra halizzah\appdata\roaming\python\python310\site-packages (from tensorflow) (26.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (1.78.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: pillow>=8 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\verra halizzah\appdata\roaming\python\python310\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pyparsing>=3 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: namex in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: rich in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.12.0->tensorflow) (14.3.3)
Requirement already satisfied: optree in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.6)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\verra halizzah\appdata\roaming\python\python310\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\verra halizzah\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\VERRA HALIZZAH\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [1]:
import os
import shutil
import random
import hashlib
from pathlib import Path
from collections import defaultdict

import pandas as pd
import numpy as np
from PIL import Image, UnidentifiedImageError
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
DATASET_RAW = "DatasetBatikRaw"
DATASET_SPLIT = "DatasetBatikFix"
WORK_DIR = "Dataset_Audit"


TRAIN_RATIO = 0.7
VAL_RATIO = 0.2
TEST_RATIO = 0.1
RANDOM_SEED = 42

assert abs(TRAIN_RATIO + VAL_RATIO + TEST_RATIO - 1.0) < 1e-8
os.makedirs(WORK_DIR, exist_ok = True)

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

print("Config Siap")

Config Siap

In [6]:
valid_ext = {".jpg", ".jpeg", ".png"}
records = []
corrupted_files = []

class_names = sorted([
    d for d in os.listdir(DATASET_RAW)
    if os.path.isdir(os.path.join(DATASET_RAW, d))
])

for class_name in class_names:
    class_dir = os.path.join(DATASET_RAW, class_name)
    files = sorted(os.listdir(class_dir))

    for fname in files:
        fpath = os.path.join(class_dir, fname)
        ext = Path(fname).suffix.lower()
        
        if ext not in valid_ext:
            continue
        
        try:
            with Image.open(fpath) as img:
                img.verify()
            
            with Image.open(fpath) as img:
                width, height = img.size
                mode = img.mode
                
            file_size = os.path.getsize(fpath)
            
            records.append({
                "class_name": class_name,
                "filename": fname,
                "filepath": fpath,
                "ext": ext,
                "width": width,
                "height": height,
                "aspect_ratio": round(width / height, 4) if height > 0 else None,
                "file_size_bytes": file_size,
                "mode": mode,
                "is_corrupt": False
            })
        except (UnidentifiedImageError, OSError, Exception) as e:
            corrupted_files.append({
                "class_name": class_name,
                "filename": fname,
                "filepath": fpath,
                "error": str(e)
            })

df = pd.DataFrame(records)
df_corrupt = pd.DataFrame(corrupted_files)

df.to_csv(os.path.join(WORK_DIR, "dataset_metadata.csv"), index=False)
df_corrupt.to_csv(os.path.join(WORK_DIR, "corrupted_files.csv"), index=False)

print(f"Total valid images: {len(df)}")
print(f"Total corrupted images: {len(df_corrupt)}")
print("Saved: dataset_metadata.csv, corrupted_files.csv")

Total valid images: 3000
Total corrupted images: 0
Saved: dataset_metadata.csv, corrupted_files.csv

In [14]:
def file_md5(path, chunk_size=8192):
    md5 = hashlib.md5()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            md5.update(chunk)
    return md5.hexdigest()

hashes = []
for fp in df["filepath"]:
    hashes.append(file_md5(fp))

df["md5"] = hashes

dup_groups = df.groupby("md5").filter(lambda x: len(x) > 1).sort_values("md5")
dup_groups.to_csv(os.path.join(WORK_DIR, "duplicate_exact_files.csv"), index=False)

print(f"Total exact-duplicate entries: {len(dup_groups)}")
print("Saved: duplicate_exact_files.csv")
dup_groups.head(20)

Total exact-duplicate entries: 0
Saved: duplicate_exact_files.csv

Empty DataFrame
Columns: [class_name, filename, filepath, ext, width, height, aspect_ratio, file_size_bytes, mode, is_corrupt, md5]
Index: []

In [15]:
cross_class_dup = (
    df.groupby("md5")["class_name"]
      .nunique()
      .reset_index(name="num_classes")
)

cross_class_dup = cross_class_dup[cross_class_dup["num_classes"] > 1]

if len(cross_class_dup) > 0:
    cross_class_detail = df[df["md5"].isin(cross_class_dup["md5"])]
    cross_class_detail.to_csv(os.path.join(WORK_DIR, "cross_class_duplicates.csv"), index=False)
    print(f"WARNING: ditemukan {len(cross_class_dup)} hash duplicate lintas kelas!")
    display(cross_class_detail.head(20))
else:
    print("Tidak ada exact duplicate lintas kelas.")

Tidak ada exact duplicate lintas kelas.

In [20]:
if os.path.exists(DATASET_SPLIT):
    shutil.rmtree(DATASET_SPLIT)
    
for split in ["train", "validation", "test"]:
    os.makedirs(os.path.join(DATASET_SPLIT, split), exist_ok = True)
    
split_records = []
    
for class_name in class_names:
    class_df = df[df["class_name"] == class_name].copy()
    
    # shuffle reproducible
    class_df = class_df.sample(frac=1, random_state=RANDOM_SEED).reset_index(drop=True)
    
    n_total = len(class_df)
    n_train = int(n_total * TRAIN_RATIO)
    n_val = int(n_total * VAL_RATIO)
    n_test = n_total - n_train - n_val
    
    train_df = class_df.iloc[:n_train]
    val_df = class_df.iloc[n_train:n_train+n_val]
    test_df = class_df.iloc[n_train+n_val:]
    
    split_map = [
        ("train", train_df),
        ("validation", val_df),
        ("test", test_df)
    ]
    
    for split_name, split_df in split_map:
        class_split_dir = os.path.join(
            DATASET_SPLIT, split_name, class_name)
        os.makedirs(class_split_dir, exist_ok=True)
        
        for _, row in split_df.iterrows():
            src = row["filepath"]
            dst = os.path.join(class_split_dir, row["filename"])
            shutil.copy2(src, dst)
            
            split_records.append({
                "class_name": class_name,
                "filename": row["filename"],
                "filepath": src,
                "split": split_name
            })

split_df_all = pd.DataFrame(split_records)
split_df_all.to_csv(os.path.join(WORK_DIR, "split_manifest.csv"), index=False)

print("Split reproducible selesai.")
print(split_df_all["split"].value_counts())

Split reproducible selesai.
split
train         2100
validation     600
test           300
Name: count, dtype: int64

In [21]:
summary = split_df_all.groupby(["split", "class_name"]).size().unstack(fill_value=0)
display(summary)

print("Train total:", (split_df_all["split"] == "train").sum())
print("Validation total:", (split_df_all["split"] == "validation").sum())
print("Test total:", (split_df_all["split"] == "test").sum())

class_name,batik_betawi,batik_bokor_kencono,batik_buketan,batik_dayak,batik_jlamprang,batik_kawung,batik_liong,batik_mega_mendung,batik_parang,batik_sekarjagad,batik_sidoluhur,batik_sidomukti,batik_sidomulyo,batik_singa_barong,batik_srikaton,batik_tribusono,batik_tujuh_rupa,batik_tuntrum,batik_wahyu_tumurun,batik_wirasat
split,,,,,,,,,,,,,,,,,,,,
test,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
train,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105,105
validation,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30

Train total: 2100
Validation total: 600
Test total: 300